-- Cost Tracking & Document Storage Migration
-- Date: 2026-02-02
-- Description: Add price fields, cost logging tables, documents table with traceability

-- =============================================
-- WAREHOUSE ITEMS - Add unit cost (per pcs)
-- =============================================
ALTER TABLE warehouse_items 
ADD COLUMN IF NOT EXISTS unit_cost DECIMAL(15,2);

COMMENT ON COLUMN warehouse_items.unit_cost IS 'Harga per pcs (normalized unit)';

-- =============================================
-- WAREHOUSE CHEMICALS - Add total price & unit cost base
-- =============================================
ALTER TABLE warehouse_chemicals 
ADD COLUMN IF NOT EXISTS total_price DECIMAL(15,2);

ALTER TABLE warehouse_chemicals 
ADD COLUMN IF NOT EXISTS unit_cost_base DECIMAL(15,4);

COMMENT ON COLUMN warehouse_chemicals.total_price IS 'Total harga per bottle/package';
COMMENT ON COLUMN warehouse_chemicals.unit_cost_base IS 'Price per unit (Rp/mL atau Rp/g). Calculated from total_price/size_value. Stored to prevent drift if size_value is edited later.';

-- =============================================
-- REAGENT CATALOG - Add CoA document field
-- =============================================
ALTER TABLE reagent_catalog 
ADD COLUMN IF NOT EXISTS coa_document TEXT;

COMMENT ON COLUMN reagent_catalog.coa_document IS 'URL ke file CoA di Supabase Storage (quick access reference)';

-- =============================================
-- STANDARD CATALOG - Add CoA document field
-- =============================================
ALTER TABLE standard_catalog 
ADD COLUMN IF NOT EXISTS coa_document TEXT;

COMMENT ON COLUMN standard_catalog.coa_document IS 'URL ke file CoA di Supabase Storage (quick access reference)';

-- =============================================
-- USAGE LOGS - Add cost fields + traceability
-- =============================================
ALTER TABLE usage_logs 
ADD COLUMN IF NOT EXISTS unit_cost DECIMAL(15,4);

ALTER TABLE usage_logs 
ADD COLUMN IF NOT EXISTS total_cost DECIMAL(15,2);

ALTER TABLE usage_logs 
ADD COLUMN IF NOT EXISTS warehouse_item_id UUID;

ALTER TABLE usage_logs 
ADD COLUMN IF NOT EXISTS warehouse_type VARCHAR(20);

COMMENT ON COLUMN usage_logs.unit_cost IS 'Harga per unit saat penggunaan (snapshot)';
COMMENT ON COLUMN usage_logs.total_cost IS 'Total biaya = quantity_used × unit_cost';
COMMENT ON COLUMN usage_logs.warehouse_item_id IS 'FK to warehouse_items or warehouse_chemicals for traceability';
COMMENT ON COLUMN usage_logs.warehouse_type IS 'Type: chemical or item';

-- =============================================
-- TRAINING COST LOGS TABLE
-- =============================================
CREATE TABLE IF NOT EXISTS training_cost_logs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    training_set_id UUID REFERENCES training_sets(id) ON DELETE SET NULL,
    training_name VARCHAR(255) NOT NULL,
    executed_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    executed_by UUID REFERENCES profiles(id) ON DELETE SET NULL,
    executed_by_name VARCHAR(100),
    participants INTEGER NOT NULL,
    sets_used INTEGER NOT NULL DEFAULT 1,
    total_cost DECIMAL(15,2) NOT NULL DEFAULT 0,
    idempotency_key VARCHAR(64) UNIQUE, -- Hash untuk cegah double execution
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

-- Unique constraint on idempotency_key (primary guard for duplicates)
-- The idempotency_key is a SHA256 hash generated by the application
-- No functional index needed - we just ensure idempotency_key is UNIQUE (already defined in table)

COMMENT ON TABLE training_cost_logs IS 'Log eksekusi training dengan total biaya';
COMMENT ON COLUMN training_cost_logs.idempotency_key IS 'SHA256 hash dari training_set_id + participants + user + timestamp_minute untuk cegah duplicate';

-- Enable RLS
ALTER TABLE training_cost_logs ENABLE ROW LEVEL SECURITY;

-- RLS Policies for training_cost_logs
DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'training_cost_logs' AND policyname = 'Authenticated users can view training cost logs') THEN
        CREATE POLICY "Authenticated users can view training cost logs"
        ON training_cost_logs FOR SELECT TO authenticated
        USING (true);
    END IF;
    
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'training_cost_logs' AND policyname = 'Authenticated users can insert training cost logs') THEN
        CREATE POLICY "Authenticated users can insert training cost logs"
        ON training_cost_logs FOR INSERT TO authenticated
        WITH CHECK (true);
    END IF;
END $$;

-- =============================================
-- TRAINING COST LOG ITEMS TABLE (Enhanced Traceability)
-- =============================================
CREATE TABLE IF NOT EXISTS training_cost_log_items (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    training_cost_log_id UUID REFERENCES training_cost_logs(id) ON DELETE CASCADE NOT NULL,
    
    -- Item identification
    item_name VARCHAR(255) NOT NULL,
    item_type VARCHAR(50) NOT NULL, -- 'consumable' | 'reagent' | 'standard' | 'barang'
    
    -- Traceability: link to source batch
    catalog_id UUID,            -- FK to catalog (reagent_catalog, standard_catalog, items_catalog)
    warehouse_item_id UUID,     -- FK to warehouse_items (for consumable/barang)
    warehouse_chemical_id UUID, -- FK to warehouse_chemicals (for reagent/standard)
    
    -- Quantity & Cost snapshot (immutable at execution time)
    quantity DECIMAL(10,2) NOT NULL,
    unit VARCHAR(50),
    unit_cost DECIMAL(15,4) NOT NULL, -- Snapshot harga per unit saat eksekusi
    total_cost DECIMAL(15,2) NOT NULL,
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

COMMENT ON TABLE training_cost_log_items IS 'Detail item per eksekusi training dengan biaya dan traceability';
COMMENT ON COLUMN training_cost_log_items.catalog_id IS 'Reference to source catalog for audit trail';
COMMENT ON COLUMN training_cost_log_items.warehouse_item_id IS 'Reference to specific warehouse_items batch used';
COMMENT ON COLUMN training_cost_log_items.warehouse_chemical_id IS 'Reference to specific warehouse_chemicals batch used';
COMMENT ON COLUMN training_cost_log_items.unit_cost IS 'Price snapshot at execution time - immutable';

-- Enable RLS
ALTER TABLE training_cost_log_items ENABLE ROW LEVEL SECURITY;

-- RLS Policies for training_cost_log_items
DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'training_cost_log_items' AND policyname = 'Authenticated users can view training cost log items') THEN
        CREATE POLICY "Authenticated users can view training cost log items"
        ON training_cost_log_items FOR SELECT TO authenticated
        USING (true);
    END IF;
    
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'training_cost_log_items' AND policyname = 'Authenticated users can insert training cost log items') THEN
        CREATE POLICY "Authenticated users can insert training cost log items"
        ON training_cost_log_items FOR INSERT TO authenticated
        WITH CHECK (true);
    END IF;
END $$;

-- =============================================
-- DOCUMENTS TABLE (Centralized Document Library)
-- =============================================
CREATE TABLE IF NOT EXISTS documents (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    
    -- Document metadata
    name VARCHAR(255) NOT NULL,          -- Display name
    document_type VARCHAR(20) NOT NULL,  -- 'msds' | 'coa'
    file_url TEXT NOT NULL,              -- Supabase Storage URL
    file_size INTEGER,                   -- Bytes
    mime_type VARCHAR(100) DEFAULT 'application/pdf',
    
    -- Catalog reference for organization
    catalog_type VARCHAR(20) NOT NULL,   -- 'reagent' | 'standard'
    catalog_id UUID NOT NULL,            -- FK to reagent_catalog or standard_catalog
    
    -- Audit
    uploaded_by UUID REFERENCES profiles(id) ON DELETE SET NULL,
    uploaded_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

-- Ensure columns exist if table was created before with different schema
ALTER TABLE documents ADD COLUMN IF NOT EXISTS name VARCHAR(255);
ALTER TABLE documents ADD COLUMN IF NOT EXISTS document_type VARCHAR(20);
ALTER TABLE documents ADD COLUMN IF NOT EXISTS file_url TEXT;
ALTER TABLE documents ADD COLUMN IF NOT EXISTS file_size INTEGER;
ALTER TABLE documents ADD COLUMN IF NOT EXISTS mime_type VARCHAR(100);
ALTER TABLE documents ADD COLUMN IF NOT EXISTS catalog_type VARCHAR(20);
ALTER TABLE documents ADD COLUMN IF NOT EXISTS catalog_id UUID;
ALTER TABLE documents ADD COLUMN IF NOT EXISTS uploaded_by UUID;
ALTER TABLE documents ADD COLUMN IF NOT EXISTS uploaded_at TIMESTAMP WITH TIME ZONE DEFAULT NOW();
ALTER TABLE documents ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW();
ALTER TABLE documents ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW();

COMMENT ON TABLE documents IS 'Centralized document library for MSDS and CoA files. Source of truth for document management.';

-- Enable RLS
ALTER TABLE documents ENABLE ROW LEVEL SECURITY;

-- RLS Policies for documents
DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'documents' AND policyname = 'Authenticated users can view documents') THEN
        CREATE POLICY "Authenticated users can view documents"
        ON documents FOR SELECT TO authenticated
        USING (true);
    END IF;
    
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'documents' AND policyname = 'Authenticated users can insert documents') THEN
        CREATE POLICY "Authenticated users can insert documents"
        ON documents FOR INSERT TO authenticated
        WITH CHECK (true);
    END IF;
    
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'documents' AND policyname = 'Authenticated users can delete documents') THEN
        CREATE POLICY "Authenticated users can delete documents"
        ON documents FOR DELETE TO authenticated
        USING (true);
    END IF;
END $$;

-- =============================================
-- INDEXES FOR PERFORMANCE
-- =============================================
CREATE INDEX IF NOT EXISTS idx_training_cost_logs_executed_at 
ON training_cost_logs(executed_at DESC);

CREATE INDEX IF NOT EXISTS idx_training_cost_logs_training_set_id 
ON training_cost_logs(training_set_id);

CREATE INDEX IF NOT EXISTS idx_training_cost_logs_idempotency 
ON training_cost_logs(idempotency_key);

CREATE INDEX IF NOT EXISTS idx_training_cost_log_items_log_id 
ON training_cost_log_items(training_cost_log_id);

CREATE INDEX IF NOT EXISTS idx_training_cost_log_items_warehouse 
ON training_cost_log_items(warehouse_item_id, warehouse_chemical_id);

CREATE INDEX IF NOT EXISTS idx_usage_logs_total_cost 
ON usage_logs(total_cost) WHERE total_cost IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_usage_logs_warehouse 
ON usage_logs(warehouse_item_id, warehouse_type) WHERE warehouse_item_id IS NOT NULL;

-- Documents indexes
CREATE INDEX IF NOT EXISTS idx_documents_catalog 
ON documents(catalog_type, catalog_id);

CREATE INDEX IF NOT EXISTS idx_documents_type 
ON documents(document_type);

-- Full-text search index for document names (using english config as fallback)
CREATE INDEX IF NOT EXISTS idx_documents_name_search 
ON documents USING gin(to_tsvector('english', name));

-- =============================================
-- VERIFY MIGRATION
-- =============================================
DO $$
BEGIN
    RAISE NOTICE '✅ Migration completed successfully';
    RAISE NOTICE '';
    RAISE NOTICE 'Schema changes:';
    RAISE NOTICE '  - warehouse_items: +unit_cost';
    RAISE NOTICE '  - warehouse_chemicals: +total_price, +unit_cost_base';
    RAISE NOTICE '  - reagent_catalog: +coa_document';
    RAISE NOTICE '  - standard_catalog: +coa_document';
    RAISE NOTICE '  - usage_logs: +unit_cost, +total_cost, +warehouse_item_id, +warehouse_type';
    RAISE NOTICE '';
    RAISE NOTICE 'New tables:';
    RAISE NOTICE '  - training_cost_logs (with idempotency_key)';
    RAISE NOTICE '  - training_cost_log_items (with full traceability)';
    RAISE NOTICE '  - documents (centralized library)';
END $$;
