import { NextResponse } from 'next/server';
import { authService, backupService } from '@/lib/services';

/**
 * GET /api/admin/backup/download
 * Download a backup ZIP file (Admin & Manager only)
 */
export async function GET() {
    try {
        // Check authentication
        const { user } = await authService.getSession();

        if (!user) {
            return NextResponse.json(
                { error: 'Unauthorized: Please login first' },
                { status: 401 }
            );
        }

        // Check user role (admin or manager)
        if (user.role !== 'admin' && user.role !== 'manager') {
            return NextResponse.json(
                { error: 'Forbidden: Admin or Manager access required' },
                { status: 403 }
            );
        }

        // Generate backup
        const { backup, results } = await backupService.generateBackupZip();

        // Log backup generation
        console.log('Backup generated by:', user.username);
        console.log('Backup results:', results);

        // Convert Buffer to Uint8Array for Response compatibility
        const uint8Array = new Uint8Array(backup.buffer);

        // Return ZIP file as download
        return new NextResponse(uint8Array, {
            status: 200,
            headers: {
                'Content-Type': 'application/zip',
                'Content-Disposition': `attachment; filename="${backup.filename}"`,
                'Content-Length': backup.buffer.length.toString(),
            },
        });
    } catch (error) {
        console.error('Backup download error:', error);
        return NextResponse.json(
            { error: 'Failed to generate backup' },
            { status: 500 }
        );
    }
}
